var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/doctors/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__098478e6._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_bb153325._.js")
R.c("server/chunks/ssr/[root-of-the-server]__84d7574a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_7c65e435._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_doctors_page_actions_7208bb93.js")
R.m(13228)
module.exports=R.m(13228).exports
