var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/doctors/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__641f0532._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_adb01ff2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__84d7574a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_7c65e435._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_doctors_page_actions_08056038.js")
R.m(16732)
module.exports=R.m(16732).exports
